services:
  - type: web
    name: telegram-downloader-bot
    # Switch the environment from 'python' to 'docker'
    env: docker
    # Render will automatically detect and build your Dockerfile
    # buildCommand and startCommand are now defined in the Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      # You can add other environment variables here if needed
      # - key: YTDLP_COOKIES
      #   value: "" # Set the value in the Render dashboard